name = "nightdev"
compatibility_date = "2024-01-01"

[env.production]
name = "nightdev"

[env.preview]
name = "nightdev-preview"

# Pages configuration
pages_build_output_dir = "."

# Environment variables (set these in Cloudflare dashboard)
# [vars]
# ANALYTICS_ENABLED = "true"