name = "nightdev"
compatibility_date = "2024-01-01"

[env.production]
name = "nightdev"

[env.preview]
name = "nightdev-preview"

# Pages configuration
pages_build_output_dir = "."

# KV Namespaces for analytics data storage
[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "your-kv-namespace-id-here"
preview_id = "your-preview-kv-namespace-id-here"

# Environment variables
[vars]
ANALYTICS_ENABLED = "true"
TURNSTILE_SECRET_KEY = "0x4AAAAAAByuMp3amBtzLFTqD_00DbRzj0o"

# Production environment variables
[env.production.vars]
ANALYTICS_ENABLED = "true"
TURNSTILE_SECRET_KEY = "0x4AAAAAAByuMp3amBtzLFTqD_00DbRzj0o"

# Preview environment variables  
[env.preview.vars]
ANALYTICS_ENABLED = "true"
TURNSTILE_SECRET_KEY = "0x4AAAAAAByuMp3amBtzLFTqD_00DbRzj0o"